# Generated by Django 3.2.7 on 2021-10-02 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
