# Generated by Django 3.2.7 on 2021-10-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_quote_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
